### ISSUE TITLE
Download the garbled words

### ISSUE THREAD

**Issue by githubyyf** [PHPOffice/PHPExcel#1089] opened 2016-12-16 03:55 UTC
i use yii2 write api excelDownload but the result like 
  ##![image](https://cloud.githubusercontent.com/assets/21100974/21187477/0fb82c9a-c253-11e6-8ca4-8a379704b1a0.png)
i need your help 。
think you!

01simple-download-xls.php
![image](https://cloud.githubusercontent.com/assets/21100974/21187297/6159d180-c252-11e6-9eba-9af96ef99cd8.png)
![image](https://cloud.githubusercontent.com/assets/21100974/21187324/75080d64-c252-11e6-87b5-dba077ada2c8.png)
![image](https://cloud.githubusercontent.com/assets/21100974/21187330/7e477ee6-c252-11e6-89cf-6afe978bfc0d.png)
result:
![image](https://cloud.githubusercontent.com/assets/21100974/21187352/9157d0a8-c252-11e6-9c08-27fbe182ce83.png)
@k1LoW @PowerKiKi @sgricci @Synchro @neclimdul

**Comment by Synchro** [comment] 2016-12-16 07:31
You just need to set the MIME type correctly so the browser will handle it as a download. Try doing this before calling `save`:

    header('Content-Type: application/vnd.ms-excel');

**Comment by githubyyf** [comment] 2016-12-16 10:05
![image](https://cloud.githubusercontent.com/assets/21100974/21258905/1fbbb5ae-c3ba-11e6-91ad-99346682a9f3.png)
![image](https://cloud.githubusercontent.com/assets/21100974/21258918/2e188d48-c3ba-11e6-8517-c7c1563b08b4.png)
@Synchro

**Comment by githubyyf** [comment] 2016-12-16 10:09
Or test tool problem?

**Comment by Synchro** [comment] 2016-12-16 10:24
I don't see a problem here. Excel is a binary format that's not going to be readable in a plain-text context, so that kind of output is exactly what I'd expect to see. If it was going to show a pretty spreadsheet, the test tool would need to know how to render Excel files, which is not a small task. If you save the output and try to open it in Excel, does it work? If so, you don't have a problem.

**Comment by jseliga** [comment] 2016-12-19 13:54
@githubyyf You have to set response format to "raw":
```php
Yii::$app->response->format = yii\web\Response::FORMAT_RAW;
```
And send response headers right before printing output:
```php
Yii::$app->response->send();

$objWriter->save('php://output');
```

**Comment by PowerKiKi** [comment] 2016-12-19 14:10
Closing as this is not a bug related to PHPExcel, but feel free to continue the discussion.

**Closed by PowerKiKi** 2016-12-19 14:10 UTC
