### ISSUE TITLE
Row auto height broken in Libre Office?

### ISSUE THREAD

**Issue by firegate666** [PHPOffice/PHPExcel#588] opened 2015-06-11 21:27 UTC
I tried to auto a row/cell with PHPExcel. It works awesome when I open the document with Excel itself, but it does not work with Libre Office.

I tried `$sheet->getRowDimension($row_no)->setRowHeight(-1);` and `$sheet->getDefaultRowDimension()->setRowHeight(-1);`. It does not work.

I found this old bug report here: https://phpexcel.codeplex.com/discussions/429322

Unfortunately the provided solution does not work.

Any ideas on this topic?

**Comment by mikehaertl** [comment] 2015-08-13 18:35
I seem to suffer from the same problem. Any solutions so far? Here's the code I use:

https://gist.github.com/mikehaertl/280455b503dc8c4ccddd

**Comment by Gemorroj** [comment] 2016-01-18 12:38
:+1:  auto height not working

**Comment by AdamReece-WebBox** [comment] 2016-03-24 10:13
5.0.5.2, still not working.

**Comment by mikehaertl** [comment] 2016-04-19 13:22
@MarkBaker Did you get a chance to look into this issue? It's too bad, that automatic line height in LibreOffice is broken for files generated with PHPExcel:

![phpexcel_rowheight](https://cloud.githubusercontent.com/assets/675062/14640555/61bdea8e-0642-11e6-841a-faeb45fcd5b1.png)

Maybe there's at least a workaround?

**Comment by clay89** [comment] 2016-05-01 16:25
A workaround would be very helpful.

**Comment by werwolf666** [comment] 2016-06-20 12:40
Row auto height still not working.

**Comment by DaumantasPHP** [comment] 2016-09-07 13:36
still have this issue

**Comment by PowerKiKi** [comment] 2016-09-07 15:19
@DaumantasPHP, please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue. And don't forget to mention what version of this project you are using. That way there will be more chance for the issue to be solved.

**Comment by hendricha** [comment] 2016-09-26 11:16
Here's an xls file created with PhpExcel, similarly how the above bug report reported it.
I attached a screenshot of it from LibreOffice Calc  4.2.8.2, and the preview with the expected behaviour from Google Drive.
[phpexcel.zip](https://github.com/PHPOffice/PHPExcel/files/492931/phpexcel.zip)

**Comment by MarkBaker** [comment] 2016-09-26 11:27
The developers of PHPExcel apologise that they cannot fix bugs in LibreOffice Calc

**Comment by mikehaertl** [comment] 2016-09-26 11:43
@MarkBaker Thanks. Could you maybe point us to any sources about this known issue in LibreOffice? I could not really find something.

I also understand that your library focusses on Excel - but wouldn't it be great if it also worked flawlessly with the alternatives? I may be wrong, but I think Excel as well as other spreadsheet software should all comply with the open document format, right? If so, then couldn't phpoffice also be geared to that standard? Because I somehow feel, that LibreOffice is probably closer to the standard than Excel. So if auto lineheight is specified in that standard it would be great to see support in phpoffice for it - and rather build a workaround for MS office.

I may be totally wrong with my assumptions, though.

**Comment by PowerKiKi** [comment] 2016-10-02 08:59
Closing as per [Mark's comment](https://github.com/PHPOffice/PHPExcel/issues/588#issuecomment-249544915).

**Closed by PowerKiKi** 2016-10-02 08:59 UTC

**Comment by mikehaertl** [comment] 2016-10-02 09:11
Thanks :-1:

**Comment by PowerKiKi** [comment] 2016-10-02 11:11
@mikehaertl, despite its name PHPExcel is not really geared toward a specific product, but rather a file format. So if you are able to find that there is indeed something wrong in the file generated by PHPExcel, I will gladly review it.

But I wasn't able to find anything myself. And that's why I relied on Mark's expertise on the topic to close this issue.

**Comment by leoquijano** [comment] 2016-10-02 16:29
Hi @MarkBaker , do you have the bug number in LibreOffice Calc so we can follow up there?

**Comment by str** [comment] 2017-05-17 14:53
Is it really a LibreOffice bug? Where can I verify it?

**Comment by MarkBaker** [comment] 2017-05-21 23:38
IIRC, it's https://bugs.documentfoundation.org/show_bug.cgi?id=91475

**Comment by str** [comment] 2017-05-22 10:52
@MarkBaker That issue is related to column width, not row height.

**Comment by MarkBaker** [comment] 2017-05-22 14:25
Then I'd need to double-check.... my original reference was on the original bug list on CodePlex, which has since been deleted

**Comment by eltian** [comment] 2017-09-29 19:15
I think this might be related: [https://bugs.documentfoundation.org/show_bug.cgi?id=62268](https://bugs.documentfoundation.org/show_bug.cgi?id=62268)

the height bug seems to be present since 2013... disappointing.

**Comment by xtempore** [comment] 2018-06-06 04:48
I came across this thread while trying to resolve a similar problem in my own PHP-based Excel code. It may be similar enough that the solution I eventually found can be used in PHPExcel.

I wondered if LibreOffice expected a very specific order for the DEFAULTROWHEIGHT record, so I moved it after the COLINFO records and it worked!  It's different to what the spec says, but I checked a sample and it still opened correctly in Excel and in OpenOffice Calc.

Maybe this will help someone.  Good luck!
