### ISSUE TITLE
Unable to load wsdl files after loading PHPExcel

### ISSUE THREAD

**Issue by danwguy** [PHPOffice/PHPExcel#1191] opened 2017-04-22 16:33 UTC
My company uses PHP 5.3.29, so I am stuck with it, and the problem I am having is... I am using a few WSDL files when connecting to FedEx and Endicia APIs. Everything was working fine, but I had to add in an excel importer, so I added this library. Now every time I try to use the app it throws an error 

> SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from

If I remove the "require_once('PHPExcel.php');" it works fine, but as soon as I add the PHPExcel library it starts throwing the SOAP-ERROR and will not load the WSDL file properly.

**Comment by pwsdotru** [comment] 2017-04-23 20:31
Can you please make small code example for reproduce this error?

**Comment by danwguy** [comment] 2017-04-24 00:41
Actually what I found out was it wasn't including the PHPExcel.php file, it was using the PHPExcel_IOFactory::load
So I have a SvcApiFedEx class, that calls 
`$this->client = new SoapClient("/var/www/html/myapp/lib/api/fedex/wsdl/RateService_v16.wsdl", array('trace' => 1);`

Now it works just fine normally, but if I add...
`PHPExcel_IOFactory::load("input_weights.xlsx");`
before I call the new SoapClient I will get the SoapFault Exception. If I remove the PHPExcel_IOFactory::load("input_weights.xlsx"); it will work fine again. I tried to track down exactly what was going on but I couldn't and ended up re-saving the xlsx file as a csv file and reading it in with ...
`$csv = array_map("str_getcsv", file("input_weights.csv");`

The following code should break it, create a folder in /var/www/html (I'm on linux if you didn't know), called "myapp"
so you have /var/www/html/myapp
Inside myapp create an index.php file, contents...
`require_once("PHPExcel.php");
    
    class LoadTest {

        public $data;

        public $csv;
        public function __construct() {
            $obj = PHPExcel_IOFactory::load("weights.xlsx");
            $call = new SoapClient("/var/www/html/myapp/RateService_v16.wsdl", array('trace' => 1));
        }
    }
`

Obviously you need a weights.xlsx file and a RateService_v16.wsdl file in the same directory. I am running PHP 5.3.29 (My company forces this, so I cannot change that.

I hope this helps. I will be more than happy to upload a tiny app that will demonstrate this happening if need be. Thank you for your help.

**Comment by PowerKiKi** [comment] 2017-04-24 00:50
Duplicate of https://github.com/PHPOffice/PhpSpreadsheet/issues/74, migrate to PhpSpreadsheet to solve it.

**Closed by PowerKiKi** 2017-04-24 00:50 UTC

**Comment by danwguy** [comment] 2017-04-24 15:31
Only problem is I can't upgrade to PHPSpreadsheet. I HAVE to use PHP 5.3.29, my company will not allow us to upgrade. Is there any possible fix for it for the version I am forced to use? Please.

**Comment by PowerKiKi** [comment] 2017-04-24 16:04
You can apply the patch yourself, it's not that big: https://github.com/PHPOffice/PhpSpreadsheet/pull/113/files
