### ISSUE TITLE
Excel2007 Without Styles throws warning

### ISSUE THREAD

**Issue by billynoah** [PHPOffice/PHPExcel#1134] opened 2017-02-21 17:51 UTC
Similar to this:  https://github.com/PHPOffice/PHPExcel/issues/558

    Warning: Invalid argument supplied for foreach() in Excel2007.php line 555

 Line in question is:

    foreach ($xmlStyles->cellStyleXfs->xf as $xf) {

Some debugging output:

    var_dump($xmlStyles->cellStyleXfs->xf);
    NULL

    var_dump($xmlStyles->cellStyleXfs);
    object(SimpleXMLElement)#656 (0) {}

I opened the xlsx file in question, resaved it and the error is gone.  Assuming this error is related to some minor issue in the file.  Would still be good to resolve - perhaps just a simple check against the property in question would suffice.

**Comment by PowerKiKi** [comment] 2017-02-22 02:51
We recently merged a commit for a similar issue in https://github.com/PHPOffice/PhpSpreadsheet/pull/95, so I think it would make sense to also solve this one. Would you create a PR against PhpSpreadsheet develop branch ?

**Comment by filipposisti** [comment] 2017-11-28 11:34
Hi, i did solve by putting a try{}catch{} at line 555 of Excel2007.php file where the

`foreach ($xmlStyles->cellStyleXfs->xf as $xf) {`

starts.

The issue is caused by a wrong interpretation of ISO/IEC 29500-1 standard. The minOccurs="0" for cellStyleXfs which indicates that this element is not required. The application should handle a non-existent cellStyleXfs element. My file was created by fileMaker.

**Comment by dnmange** [comment] 2018-01-09 21:55
@filipposisti  how exactly you resolved did you just put try catch and didn't modified the for loop code, i am getting this bug, thanks for your time.

**Comment by filipposisti** [comment] 2018-01-10 07:49
Hi,

the foreach loop is inside a try{}catch{} block

`try{
							foreach ($xmlStyles->cellStyleXfs->xf as $xf) {
								$numFmt = PHPExcel_Style_NumberFormat::FORMAT_GENERAL;
								if ($numFmts && $xf["numFmtId"]) {
									$tmpNumFmt = self::array_item($numFmts->xpath("sml:numFmt[@numFmtId=$xf[numFmtId]]"));
									if (isset($tmpNumFmt["formatCode"])) {
										$numFmt = (string) $tmpNumFmt["formatCode"];
									} else if ((int)$xf["numFmtId"] < 165) {
										$numFmt = PHPExcel_Style_NumberFormat::builtInFormatCode((int)$xf["numFmtId"]);
									}
								}

								$cellStyle = (object) array(
									"numFmt" => $numFmt,
									"font" => $xmlStyles->fonts->font[intval($xf["fontId"])],
									"fill" => $xmlStyles->fills->fill[intval($xf["fillId"])],
									"border" => $xmlStyles->borders->border[intval($xf["borderId"])],
									"alignment" => $xf->alignment,
									"protection" => $xf->protection,
									"quotePrefix" => $quotePrefix,
								);
								$cellStyles[] = $cellStyle;

							// add style to cellStyleXf collection
								$objStyle = new PHPExcel_Style;
								self::_readStyle($objStyle, $cellStyle);
								$excel->addCellStyleXf($objStyle);
							}
						}catch(Exception $e){

						}`

just manage the catch part as you want.

**Comment by joakimcarlsten** [comment] 2018-04-06 18:38
Same thing for me (using phpoffice/phpspreadsheet), generated a file in FileMaker and got this error. Just open and save in Excel and you're good to go.

**Closed** 2018-08-19 06:43 UTC
