### ISSUE TITLE
Apostrophes near the end of the sheet name

### ISSUE THREAD

**Issue by Vinksyunit** [PHPOffice/PHPExcel#740] opened 2015-11-18 10:33 UTC
I have an issue with PhpExcel trying to edit an XLSX file.

The issue occurs when the sheet name contains an apostrophe (For example : `FEUILLE d'ARRIVEE`).

Here is the PHP error :
`Uncaught exception 'PHPExcel_Exception' with message 'Invalid cell coordinate 'FEUILLE D'A1' in ../lib/PHPExcel-1.8.1/Classes/PHPExcel/Cell.php:590`

For the moment, we did a little work-around preventing the apostrophe, but in my opinion, it should work.

**Comment by MarkBaker** [comment] 2015-11-18 10:52
PHPExcel should handle worksheet names containing single quote without problem, can you provide either a stack trace so I can see what is going on at this point, or a working example of code that will allow me to duplicate the problem

**Comment by Vinksyunit** [comment] 2015-12-03 14:25
The user changed the Excel file template, and I forgot to do a copy. I did not manage to reproduce the issue with a new one. I think it can be due to an old Excel version. None of our other users are impacted, so you can close the issue for the moment. 

I will re-open one with the model attached if it occurs again.

**Comment by Vinksyunit** [comment] 2016-08-01 13:52
Today I got another similar issue with one spreadsheet made by one of our customer.

After some research, I manage to reproduce the problem :

If the name of the sheet is `Fiche d'action`, there is an issue. But if we put `Fiche d'action par utilisateur`, everything if working fine.

The problem seems to be due to this line : [Excel 2007 reader](https://github.com/PHPOffice/PHPExcel/blob/c70e289dacc794ac37e11c4f5ee035b126aea8df/Classes/PHPExcel/Reader/Excel2007.php#L1562)

I do not understand why this substitution is made and I do not want to cause more issues removing it. Generally, a line is here for a reason. Do you have any clue about the goal of this line and the best way to correct our issue ?

Here is the result of the substitution :
```
'Fiche d''action'!$A$1:$N$19
// Becomes
'Fiche d'$A$1:$N$19
// so no more "!" and the print area is now wrong resulting in a crash.
```

**Comment by PowerKiKi** [comment] 2016-08-26 14:18
@Vinksyunit the origin of this line goes all the way back to the [very first commit of this project](https://github.com/PHPOffice/PHPExcel/blob/509f27e5c601c002090af18a5dd545b06b7183ca/Classes/PHPExcel/Reader/Excel2007.php#L1269). Unfortunately I don't think anybody know what was the original purpose.

However if you or @rudyZanotti can submit a PR, that includes unit tests, against https://github.com/PHPOffice/PhpSpreadsheet's develop branch, I'll merge it.

**Comment by Vinksyunit** [comment] 2016-08-26 18:40
@PowerKiKi, thank you for the answer. 

Pull request submitted #990. I tried a few things but I did not manage to understand the purpose of this line. All cases where this regular expression was matching were causing the same type of issues.

**Comment by PowerKiKi** [comment] 2016-08-27 03:40
Actually I had a better look at this issue, and I can't reproduce it. Where does your file come from ? Could you please share code and file that could allow us to reproduce ?

This code:
```php
<?php

require 'Classes/PHPExcel.php';

$filename = 'test.xlsx';
$originalTitle = "FEUILLE d'ARRIVEE";

// Write file
$workbook = new PHPExcel();
$sheet = $workbook->getActiveSheet();
$sheet->setTitle($originalTitle);
$writer = new PHPExcel_Writer_Excel2007($workbook);
$writer->save($filename);

// Read file
$reloadedWorkbook = PHPExcel_IOFactory::load($filename);
$title = $reloadedWorkbook->getActiveSheet()->getTitle();
var_dump($title === $originalTitle);
echo 'PHPExcel version: ' . `git describe --always`;
```

will output as expected:
```
bool(true)
PHPExcel version: 1.8.1
```

So that means that PHPExcel is able to write and read sheet titles containing apostrophes. And also that LibreOffice Calc 5.1 is able to read files written by PHPExcel and PHPExcel is able to read files written by LibreOffice.

@rudyZanotti feel free to participate here, if you can help us reproduce the case.

**Comment by Vinksyunit** [comment] 2016-08-27 08:59
Thanks for your work. I just find the sheet where we had the issue.

See below the error :

```
Type: PHPExcel_Exception
Message: Invalid cell coordinate 'LIVRET D'A1
File: ****/PHPExcel-1.8.1/Classes/PHPExcel/Cell.php
Line: 590
```
[sample_issue.xlsx](https://github.com/PHPOffice/PHPExcel/files/440564/sample_issue.xlsx)

We read the file and search for specific content in it. In case we found it, we replace it.

I join you a short sample of the code linked to PHPExcel 

```php
$excelTemplate = \PHPExcel_IOFactory::createReader('Excel2007');
$excelTemplate->setIncludeCharts(true);
$this->workbook = $excelTemplate->load($this->datum->getForm()->getExcelFileName());

// Doing stuff not related to PHPExcel

if ($this->workbook->getSheetCount() > 0) {
	$this->workbook->setActiveSheetIndex(0);
}
// the issue occurs to the line below
$objWriter = \PHPExcel_IOFactory::createWriter($this->workbook, 'Excel2007');
```

**Comment by PowerKiKi** [comment] 2016-10-02 11:28
I could reproduce with your file and the following code:
```php
<?php

require_once 'Classes/PHPExcel.php';

$excelTemplate = \PHPExcel_IOFactory::createReader('Excel2007');
$workbook = $excelTemplate->load('sample_issue.xlsx');

$objWriter = \PHPExcel_IOFactory::createWriter($workbook, 'Excel2007');
$objWriter->save('out.xlsx'); // crash here
```

Contrary to what your code implied the crash happened on `save()`, not on `createWriter()`. Also your file was needed to reproduce because it actually is related to the print area. My previous attempt did not have any print area specified, so the crash was not triggered.

Anyway, I merged a fix (highly inspired by your PR) in https://github.com/PHPOffice/PhpSpreadsheet/commit/e95a2670347f87dc96cca9d88a9c2e904a73bb17

**Closed by PowerKiKi** 2016-10-02 11:28 UTC
