### ISSUE TITLE
"Maximum 31 characters allowed in sheet title." Exception

### ISSUE THREAD

**Issue by dbonsch** [PHPOffice/PHPExcel#79] opened 2012-11-16 17:11 UTC
At least having a title longer than 31 characters is not that fatal to stop creating the Sheet by throwing an Exception.

Why not just use sub_str / mb_substr to cut the the title to 28 chars + 3 dots and add / throw some kind of a warning instead?

**Comment by LoranRendel** [comment] 2016-01-12 09:06
New versions of Excel supports longer names even for xls.

**Comment by MarkBaker** [comment] 2016-01-12 09:16
Fascinated in how they can retrofit a change to the limit in xls without changing the file structure. any insight in how they do it?

**Comment by LoranRendel** [comment] 2016-01-12 09:37
Oh, my mistake, actually there are 31 unicode symbols.
But if I write more symbols, MS Excel 2016 read first 31, and LibreOffice read entire string.

**Comment by 53715** [comment] 2016-02-09 18:08
I run excel 2003 on a Win XP box.
Our pay roll vendor sends an excel spreadsheet after every payroll. 
It consists of a single tab, with a 42 character name.
excel 2003 opens it without an issue.
once open, clicking on file->properties->contents show the first 37 characters and three dots because that is all the width they have for a display. In my mind they know that name is longer and are OK with it.

I have been trying to figure out what application our payroll processor uses to create the .xls file. It is generated by a server, not a person so I am 99.9% certain that it was not created by excel. I don't see anything in the file that identifies the application or publisher.

I have to find a way to read this file. The version of php excel that I used (2012 vintage according to the headers in the source files) stops dead (throws an exception) when it hits the 42 character sheet name.  I am certain that it is not used in formulas, I don't want to manually load it into excel, truncate it and save it. On that topic, you can rename the 42 character tab name but you are restricted when you do in that each intermediate name must result in a name of 31 characters or less. You can't type a letter (intermediate name length goes from 42 to 43, excel 2003 does not accept. You can't even press the delete key (intermediate name length goes from 42 to 41, excel 2003 does not accept. You can make a selection of 10 to 42 characters and press delete. the intermediate name will be between 0 and 31 characters and excel 2003 will accept that.

So what can we do to allow a sheet with a tab name longer than 31 to load? For my purposes it would be OK but less than desirable to name the tab "Sheet 1".  Truncating it to 30 characters with one reserved for a "tie breaker" could work as could some logic that would remover the common characters from the front tab names, be they at the front or the back, and leaving the unique parts of the names is another thought.

This is only tangentially related, I can not find the 31 character limit in this documentation: 
https://support.office.com/en-us/article/Excel-specifications-and-limits-16c69c74-3d6a-4aaf-ba35-e6eb276e8eaa

It lists every excel limit imaginable except a limit on tab name length.
I guess I would be happy if they called it out and said "not limited" or "limited by available memory" or "limited by file size limitations" but I can not see where they say anything one way or the other on it and excel 2003 clearly has some limitations if not an outright ban on tab names longer than 32.

I have to keep digging.
I will post more as I learn more.
In the mean time if Mark can point me in the right direction, it would be helpful.

**Comment by 53715** [comment] 2016-02-11 06:44
I was able to get the sheet from the payroll company loaded by going to the checkSheetTitle method in worksheet.php and changing the max title length from 31 to 131 which is not an ideal solution at all but it gets my employer off my back.

@MarkBaker on Jul 23, 2013 while you may not be sure how, I just demonstrated that it can and I submit that it should. @dbonsch on Nov 16, 2012 suggested truncation, we could do truncation with a tie breaker, I just demonstrated that at least in certain cases, it can be left long. I agree strongly that the as long as banks and payroll companies send us workbooks that have tabs with long names that excel 2003 has no trouble reading, then phpexcel should be able to open and read them too. It should enforce the 31 character limit in the writers, not in the readers as proposed by issue #382. I routinely "enhance" phpexcel for our own purposes. Typically it is to avoid throwing exceptions that are not warranted, just like this one. The modified code runs with perfect reliability in our domain but I have no way to vet my code to make sure that it would run in all domains so I have not submitted it. I am sure that I could write code that would address this issue and test it here, but I have no idea what to do with the code after I test it locally so that others could benefit from it

**Comment by jdufresne** [comment] 2016-05-19 03:52
I have created a minimal example repository that demonstrates this bug with the PHPExcel reader at <https://github.com/jdufresne/phpexceltest>.

In the repository is the file `test.xls` with a 50+ character sheet name. The file was created using LibreOffice. Other than changing the sheet name, nothing else was modified.

The test PHP file consists only of `PHPExcel_IOFactory::load('test.xls');`. When running `php test.php`, this fails with the following stack trace:

```
PHP Fatal error:  Uncaught exception 'PHPExcel_Exception' with message 'Maximum 31 characters allowed in sheet title.' in .../phpexceltest/vendor/phpoffice/phpexcel/Classes/PHPExcel/Worksheet.php:472
Stack trace:
#0 .../phpexceltest/vendor/phpoffice/phpexcel/Classes/PHPExcel/Worksheet.php(841): PHPExcel_Worksheet::_checkSheetTitle('Lorem ipsum dol...')
#1 .../phpexceltest/vendor/phpoffice/phpexcel/Classes/PHPExcel/Reader/Excel5.php(761): PHPExcel_Worksheet->setTitle('Lorem ipsum dol...', false)
#2 .../phpexceltest/vendor/phpoffice/phpexcel/Classes/PHPExcel/IOFactory.php(192): PHPExcel_Reader_Excel5->load('test.xls')
#3 .../phpexceltest/test.php(4): PHPExcel_IOFactory::load('test.xls')
#4 {main}
  thrown in .../phpexceltest/vendor/phpoffice/phpexcel/Classes/PHPExcel/Worksheet.php on line 472
```

**Comment by aloha0608** [comment] 2016-05-23 14:40
Just go to phpoffice/phpexcel/classess/phpexcel/Worksheet.php file and comment the following line ,

if (PHPExcel_Shared_String::CountCharacters($pValue) > 31) {
            throw new PHPExcel_Exception('Maximum 31 characters allowed in sheet title.');
        }

**Comment by 53715** [comment] 2016-05-23 18:55
@aloha0608 that is essentially that same work around described in the post of February 11th. It works but it is not a resolution of the issue.

**Comment by PowerKiKi** [comment] 2017-06-23 08:51
Duplicate of https://github.com/PHPOffice/PhpSpreadsheet/pull/177#issuecomment-309699114

**Closed by PowerKiKi** 2017-06-23 08:51 UTC
Labels: Type - Bug
