### ISSUE TITLE
reading xlsx file creates HTML reader?

### ISSUE THREAD

**Issue by bazo** [PHPOffice/PHPExcel#443] opened 2014-10-09 10:47 UTC
````
$name = 'test.xlsx';

$excel		 = \PHPExcel_IOFactory::load($name);
$sheetData	 = $excel->getActiveSheet()->toArray(NULL, FALSE, FALSE, TRUE);
````
and i get this error DOMDocument::loadHTMLFile(): Invalid char in CDATA 0x3 in file:///C:/Windows/TEMP/54366714e6daetest%20importu%20poloziek.xlsx, line: 1

wtf? phpexcel idenitfies the format as excel2007 why does it load html reader then? and why should excel load html files? what kind of bullshit is that?

**Comment by rique** [comment] 2015-06-16 16:09
Hi,
Have you found the solution to your problem ?
I'm having the exact same problem with my .xls files as soon as I try to encode the content to UTF-8

**Comment by xywei0315** [comment] 2015-12-18 05:59
I had the same problem.
I tried to change the file path to absolute path like 'D:\test.xlsx',then it worked!
I don't know the reason why...

**Comment by johntaylortoo** [comment] 2015-12-18 16:53
I was having the same problem and came across this post attempting to resolve it.  Reading through the thread a key word sparked a thought, "BINARY".  I was pulling my xlsx file from an FTP server and it defaults to FTP_ASCII.  I changed that to FTP_BINARY and PHPEXCEL now reads the file properly.

I hope that helps some of you.

**Comment by Snorvarg** [comment] 2016-08-17 18:10
Hi, I have the same error message, so I have attached an example file here: 
[example.xlsx](https://github.com/PHPOffice/PHPExcel/files/423274/example.xlsx)

The file is created in Microsoft Office 365, version 16.0.7070.2033.

If I save the file as .xls (97-2003) PHPExcel can read the file with no problem. 

Please advice.

**Comment by PowerKiKi** [comment] 2016-08-18 02:29
Can't reproduce with PHPExcel 1.8.1 (and master) with your example.xlsx and the following code:

```php
<?php

require_once 'PHPExcel/Classes/PHPExcel.php';

$name = 'example.xlsx';
$excel = \PHPExcel_IOFactory::load($name);
$sheetData = $excel->getActiveSheet()->toArray(NULL, FALSE, FALSE, TRUE);
var_dump($sheetData);
```

Would you have other information to share to reproduce your case ?

**Comment by Snorvarg** [comment] 2016-08-18 11:37
> NOTE: I just realized the problem is limited to my Windows iis installation! .xlsx files works on our linux-server. So the stuff below only happens on my Windows iis. (Less important it is working there, but you might have an idea about why it is not working there?)

Hi, I get the same error message with your code:

`DOMDocument::loadHTMLFile() [domdocument.loadhtmlfile]: Invalid char in CDATA 0x4 in file:///C:/Windows/Temp/php6CF8.tmp, line: 1 [APP\Vendor\PHPExcel\Classes\PHPExcel\Reader\HTML.php, line 427]`

Here is the callstack: (I am using cakephp, should not be important)
```
DOMDocument::loadHTMLFile() - [internal], line ??
PHPExcel_Reader_HTML::loadIntoExisting() - APP\Vendor\PHPExcel\Classes\PHPExcel\Reader\HTML.php, line 427
PHPExcel_Reader_HTML::load() - APP\Vendor\PHPExcel\Classes\PHPExcel\Reader\HTML.php, line 141
PHPExcel_IOFactory::load() - APP\Vendor\PHPExcel\Classes\PHPExcel\IOFactory.php, line 192
StudentsController::teacher_import_class() - APP\Controller\StudentsController.php, line 113
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE\Cake\Controller\Controller.php, line 486
Dispatcher::_invoke() - CORE\Cake\Routing\Dispatcher.php, line 187
Dispatcher::dispatch() - CORE\Cake\Routing\Dispatcher.php, line 162
require - APP\webroot\index.php, line 119
[main] - ROOT\index.php, line 43

```

Please note; I am uploading the file via the browsers file selector, so a temporary file is created. However, this should not be the case to the problem, since it works with an .xls file. 

Also note; The web-server is a windows iis service, running on Windows 10.

**Comment by PowerKiKi** [comment] 2016-08-18 13:58
Could you try to reproduce the problem outside of the web server and outside of cakePHP to see if they have anything to do with this ?

Also what version of PHPExcel do you use?

**Comment by Snorvarg** [comment] 2016-08-19 08:52
I use v1.8.0 of cakePHP. I don't understand how I should do to reproduce outside of the web server?

**Comment by Snorvarg** [comment] 2016-08-19 09:00
I tried your code-example outside of cake, in its own file. It works. So it is some cake-settings interfering somehow. Do you have a clue of what settings I should look for?

**Comment by PowerKiKi** [comment] 2016-08-19 09:45
Unfortunately I am not familiar enough with CakePHP to help you. Sorry about that.

Meanwhile I'll close this issue because the cause seems to be unrelated to PHPExcel.

**Closed by PowerKiKi** 2016-08-19 09:45 UTC

**Comment by aamirr** [comment] 2016-09-04 17:20
@PowerKiKi, issue still exists ) take a look at attached file, PHPExcel identifies this file as HTML.
[psemf-2474-eiuyr.xlsx](https://github.com/PHPOffice/PHPExcel/files/454021/psemf-2474-eiuyr.xlsx)

But off course only works is the older format, can convert the same file here http://convertstandard.com/Xlsx2Xls.aspx and it works

**Comment by MarkBaker** [comment] 2016-09-04 18:04
It fails for the same reason they always fail, non-standard namespacing.

**Comment by aamirr** [comment] 2016-09-04 20:10
@MarkBaker Yup I got that, what I meant is we have to have the issue open so more chances of a workaround or even better a PR may appear ) thanks anyways.

**Comment by MarkBaker** [comment] 2016-09-04 20:14
Solution: complete rewrite of XLSX Reader, that's not quick, and I doubt very much that anybody will provide a PR..... but there's many causes that could create a situation where files are misinterpreted or unreadable..... one all-encompassing "issue" is an issue that can never be resolved, it requires specific issues for specific reasons that can be individually addressed

**Comment by uppfinnarjocke** [comment] 2016-10-19 08:20
@MarkBaker  - I have a problem with PHP 7 since 7.0.12. I have no problem reading the xlsx file, but from a CMS share. I have to copy my file from it to a directory under C:\

**My errors are these when reading from a CMS-share like //server/share/directory/file.xlsx** :
```
Warning: DOMDocument::loadHTML(): Invalid char in CDATA 0x3 in Entity, line: 1 in C:\Apache24\htdocs\phpexcel\Classes\PHPExcel\Reader\HTML.php on line 478

Warning: DOMDocument::loadHTML(): Invalid char in CDATA 0x4 in Entity, line: 1 in C:\Apache24\htdocs\phpexcel\Classes\PHPExcel\Reader\HTML.php on line 478

Warning: DOMDocument::loadHTML(): Invalid char in CDATA 0x14 in Entity, line: 1 in C:\Apache24\htdocs\phpexcel\Classes\PHPExcel\Reader\HTML.php on line 478
```

**Comment by a-n-dcruz** [comment] 2016-11-28 01:42
I'm encountering a similar issue. PHPExcel can read xls files with no issues but when it comes to xlsx files I encounter a weird behavior. I created a file using MS Excel 2013 then saved it twice. The first save I named "aaaa.xlsx" the second I named "画面.xlsx". Now when I try to read "aaaa.xlsx", it works okay but every time I try to read "画面.xlsx", I get the error: **DOMDocument::loadHTML():Invalid char in CADATA 0x3 in Entity, line: 1** When checking the output for the identify function, "aaaa.xlsx" is identified as type Excel2007 but "画面.xlsx" is identified as HTML. Basically they were created using the same program and they have the same contents, the only difference is the filename.

Can someone give me suggestions in resolving this? Most of the files my project would be reading have japanese filenames.

**Comment by wesood** [comment] 2017-04-18 20:38
If you can catch the type before it processes it, it will work. 

`//XLSX import breaks on the server : this below fixes the error 
if($FileType == "xlsx"){
	PHPExcel_Settings::setZipClass(\PHPExcel_Settings::PCLZIP);
}
$inputFileType = PHPExcel_IOFactory::identify($inputFileName);
`
Found the fix here
[http://stackoverflow.com/questions/40797346/yii2-phpoffice-phpexcel-identifies-xlsx-file-as-html](url)

**Comment by Guicom** [comment] 2017-07-27 07:54
@wesood thx for the fix, he save my time !!

**Comment by arya108** [comment] 2018-12-18 18:19
@wesood ditto!
