### ISSUE TITLE
How let PHPExcel return the correct filetype with identify() method

### ISSUE THREAD

**Issue by kondonator** [PHPOffice/PHPExcel#1076] opened 2016-12-05 12:39 UTC
I have examined if the latest PHPExcel is available to parse **xls**, **xlsx** and **csv** files those the user uploads.

The environment is with Laravel 5.1, PHP 5.6.10 and MAMP 3.4.
To install PHPExcel, I used the command "**sudo composer require phpoffice/phpexcel**" and it seemed suceeded.
First I followed the sample code with my own sample file as below:

```php
$filetype = PHPExcel_IOFactory::identify($dirpath . '/', $filename);
$objReader = PHPExcel_IOFactory::createReader($filetype);
$objPHPExcel = $objReader->load($dirpath . '/', $filename);
var_dump($objPHPExcel->getActiveSheet()->toArray(null,true,true,true));
```

What I found on the browser was as below:
`array(1) { [1]=> array(1) { ["A"]=> NULL } }`

Ok, maybe something wrong.
Next I uploaded the file "**PHPExcel_1.8.0_pdf/Documentation/Examples/Reading WorkBook Data/sampleData/example1.xls**".

I expected the system parsed the file and displayed the contents on the browser but what I saw again was same as the previous.

To identify the problem, I modified the code as below:

```php
$mimetype = $file->getClientMimeType();
$filetype = PHPExcel_IOFactory::identify($dirpath . '/', $filename);
echo 'Mime Type: ' . $mimetype . '<br>';
echo 'File Type: ' . $filetype . '<br>';

$objReader = PHPExcel_IOFactory::createReader($filetype);
$objPHPExcel = $objReader->load($dirpath . '/', $filename);
var_dump($objPHPExcel->getActiveSheet()->toArray(null,true,true,true));
```

Again I uploaded the file. Next I saw on the brower was:

```
Mime Type: application/vnd.ms-excel
File Type: CSV
array(1) { [1]=> array(1) { ["A"]=> NULL } }
```

Now that I found the system failed to recognise the filetype with identify() method.
What should I do to fix the problem and to let the system find out the filetype correctly with identify()?
Or please let me know what identify() method is influenced by and what should I check?

Thanks in advance.

**Comment by PowerKiKi** [comment] 2016-12-05 13:33
What is the value of `$dirpath . '/', $filename` ?

**Comment by PowerKiKi** [comment] 2016-12-05 13:36
Most likely it is a duplicate of https://github.com/PHPOffice/PHPExcel/issues/1071#issuecomment-263464073. Let me know if it doesn't work.

**Closed by PowerKiKi** 2016-12-05 13:36 UTC

**Comment by kondonator** [comment] 2016-12-06 05:11
Thanks to your feedbacks, I modified the code as below:

```
$mimetype = $file->getClientMimeType();
$filetype = PHPExcel_IOFactory::identify($dirpath . '/', $filename);
echo 'Mime Type: ' . $mimetype . '<br>';
echo 'File Type: ' . $filetype . '<br>';
echo 'File Path: ' . $dirpath . '/', $filename . '<br>';
\PHPExcel_Settings::setZipClass(\PHPExcel_Settings::PCLZIP);
$objReader = PHPExcel_IOFactory::createReader($filetype);

$objPHPExcel = $objReader->load($dirpath . '/', $filename);
var_dump($objPHPExcel->getActiveSheet()->toArray(null,true,true,true));
```

What I saw on the browser is like this:

```
Mime Type: application/vnd.ms-excel
File Type: CSV
File Path: /Users/kondonator/Documents/htdocs/payroll/storage/records/10/example1.xls
array(1) { [1]=> array(1) { ["A"]=> NULL } }
```

File Path is the correct value but the system still could not get the correct file type.
What can I do next?
Thanks.

**Comment by PowerKiKi** [comment] 2016-12-06 08:43
Use `setZipClass()` before `identify()`.

**Comment by kondonator** [comment] 2016-12-06 09:08
Thanks. When I uploaded  "**PHPExcel_1.8.0_pdf/Documentation/Examples/Reading WorkBook Data/sampleData/example1.xls**" I got the following error.

```
ErrorException in ZipArchive.php line 173:
Undefined variable: contents
in ZipArchive.php line 173
at HandleExceptions->handleError('8', 'Undefined variable: contents', '/Users/kondonator/Documents/htdocs/payroll/vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php', '173', array('fileName' => '_rels/.rels', 'list' => '0', 'listCount' => '1', 'list_index' => '-1', 'i' => '1', 'extracted' => '0', 'filename' => 'rels/.rels')) in ZipArchive.php line 173
at PHPExcel_Shared_ZipArchive->getFromName('_rels/.rels') in Excel2007.php line 327
at PHPExcel_Reader_Excel2007->_getFromZipArchive(object(PHPExcel_Shared_ZipArchive), '_rels/.rels') in Excel2007.php line 97
at PHPExcel_Reader_Excel2007->canRead('/Users/kondonator/Documents/htdocs/payroll/storage/records/10/') in IOFactory.php line 280
at PHPExcel_IOFactory::createReaderForFile('/Users/kondonator/Documents/htdocs/payroll/storage/records/10/') in IOFactory.php line 205
at PHPExcel_IOFactory::identify('/Users/kondonator/Documents/htdocs/payroll/storage/records/10/', 'example1.xls') in TimecardsController.php line 149
at TimecardsController->doUpload(object(Request))
:
```

I found the similar problem on [https://github.com/PHPOffice/PHPExcel/issues/535](url) but it was not solved.
What should I do next?
Thanks for your help.

**Comment by PowerKiKi** [comment] 2016-12-06 10:26
I am running out of ideas here... what do you get if running `composer show phpoffice/phpexcel` ? is it PHPExcel 1.8.1 ?

**Comment by kondonator** [comment] 2016-12-06 11:19
Thanks for your input.
I got the following:

```
$ composer show phpoffice/phpexcel
name     : phpoffice/phpexcel
descrip. : PHPExcel - OpenXML - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
keywords : OpenXML, excel, php, spreadsheet, xls, xlsx
versions : * 1.8.1
type     : library
license  : LGPL
source   : [git] https://github.com/PHPOffice/PHPExcel.git 372c7cbb695a6f6f1e62649381aeaa37e7e70b32
dist     : [zip] https://api.github.com/repos/PHPOffice/PHPExcel/zipball/372c7cbb695a6f6f1e62649381aeaa37e7e70b32 372c7cbb695a6f6f1e62649381aeaa37e7e70b32
names    : phpoffice/phpexcel

autoload
psr-0
PHPExcel => Classes/

requires
ext-xml *
ext-xmlwriter *
php >=5.2.0
```

Could this information be helpful to you?

**Comment by PowerKiKi** [comment] 2016-12-06 14:51
Thank you, but unfortunately it doesn't help us much. You correctly have the latest version 1.8.1.

I just tried here on PHPExcel 1.8.1 and PHP 5.6 and 7.0 the following code

```
<?php

require 'Classes/PHPExcel.php';

$inputFileName = './Documentation/Examples/Reading WorkBook Data/sampleData/example1.xls';
\PHPExcel_Settings::setZipClass(\PHPExcel_Settings::ZIPARCHIVE);
$a = PHPExcel_IOFactory::identify($inputFileName);

\PHPExcel_Settings::setZipClass(\PHPExcel_Settings::PCLZIP);
$b = PHPExcel_IOFactory::identify($inputFileName);

var_dump($a, $b);
```

Put that in `vendor/phpoffice/phpexcel/test.php`, then `cd vendor/phpoffice/phpexcel && php test.php`. It should give you this:

```
$ php test.php 
string(6) "Excel5"
string(6) "Excel5"
```

Is it not the case ?

**Comment by kondonator** [comment] 2016-12-08 08:28
Finally I found the cause.

`$filetype = PHPExcel_IOFactory::identify($dirpath . '/', $filename);`
should be 
`$filetype = PHPExcel_IOFactory::identify($dirpath . '/' . $filename);`

Everything works after I modified the code.
Thanks a million for your kind support.

**Comment by Holisollogistics** [comment] 2017-04-03 04:59
Hi guys please help me out in this issue...
the following code returns the error in some cases...

Code::
\Excel::load(public_path() . '/calculator/' . $name, function($results) { });

Error ::
ErrorException in ZipArchive.php line 173:
Undefined variable: contents

**Comment by PowerKiKi** [comment] 2017-04-03 05:41
@Holisollogistics, please don't copy/paste your question in several threads

**Comment by vijaykumarvj143** [comment] 2018-02-28 08:43
How to read Excel file without passing its dirpath but passing only excel file name to PHPExcel.

**Comment by jamesexperts** [comment] 2018-07-25 12:14
Just update
PHPExcel_Settings::setZipClass(PHPExcel_Settings::PCLZIP);
to
PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);
