### ISSUE TITLE
Apostrophes in my sheet name

### ISSUE THREAD

**Issue by rudyZanotti** [PHPOffice/PHPExcel#988] opened 2016-08-26 12:18 UTC
I have to edit some XLSX but when my sheet name contains an apostrophe (ex : "Feuille d'action") an issue occurs. 

Here is the PHP error :
`Uncaught exception 'PHPExcel_Exception' with message 'Invalid cell coordinate 'FEUILLE D'A1' in ../lib/PHPExcel-1.8.1/Classes/PHPExcel/Cell.php:590`

From my point of view, it should work.

**Comment by rudyZanotti** [comment] 2016-08-26 12:29
I just found a similar issue : https://github.com/PHPOffice/PHPExcel/issues/740

**Comment by PowerKiKi** [comment] 2016-08-26 14:12
Closing as duplicate of #740. Let's continue the discussion in the older issue please.

**Closed by PowerKiKi** 2016-08-26 14:12 UTC
