### ISSUE TITLE
Valid directory to TrueType Font files not specified

### ISSUE THREAD

**Issue by marcinrosinski** [PHPOffice/PHPExcel#556] opened 2015-05-06 17:21 UTC
Hi,

Looks like 1.8.1 update introduced some bug which now throws the following Exception (all works fine under 1.8.0, no exception is thrown in there):

```
Uncaught exception 'PHPExcel_Exception' with message 'Valid directory to TrueType Font files not specified' in MY_PATH/vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/Font.php:426
```

Yes, I can catch that exception but why there is no problem with it under 1.8.0 only in 1.8.1, looks to me like a bug.

**Comment by FHenry** [comment] 2015-05-20 12:44
Affect me also

**Comment by zekial** [comment] 2015-09-30 06:51
I also had to go back to 1.8.0 because of this

**Comment by maxiwheat** [comment] 2015-10-09 18:41
I have the same issue when I try to use PHPExcel_Shared_Font::setAutoSizeMethod(PHPExcel_Shared_Font::AUTOSIZE_METHOD_EXACT);

**Comment by Easthy** [comment] 2015-11-22 17:30
version 1.8.0 has this error too.
 PHPExcel_Shared_Font::setAutoSizeMethod(PHPExcel_Shared_Font::AUTOSIZE_METHOD_EXACT);$objPHPExcel->getActiveSheet()->getColumnDimensionByColumn($col+1)->setAutoSize(true); 

[Sun Nov 22 20:18:40 2015] [error] [client 172.16.0.50] PHP PHPExcel_Exception:  Valid directory to TrueType Font files not specified in /srv/www/test/app/webroot/PHPExcelClasses/PHPExcel/Shared/Font.php on line 428,i$

**Comment by christhomas** [comment] 2015-12-02 10:40
I'm having this exact problem now, I'm going to try a previous version

**Comment by christhomas** [comment] 2015-12-02 10:43
downgrading to 1.8.0 also solved the problem for me as well, I updated composer to use 

"phpoffice/phpexcel": "1.8.0"

and the problem disappeared and files are rendering again

**Comment by MarkBaker** [comment] 2015-12-02 11:02
OK! I get the picture! I've managed to introduce a bug!

While you're all busy downgrading, has anybody actually tried to figure out the actual problem?

**Comment by sharpensteel** [comment] 2015-12-13 17:04
hi guys!
i debugged a bit, 
there is exception at PHPExcel/Shared/Font.php, in line 272:

```php
$columnWidthAdjust = ceil(self::getTextWidthPixelsExact('n', $font, 0) * 1.07);
```
in old versions this line was inside try/catch block, so exception was suppressed.
exception:
```php
if (!file_exists(self::$trueTypeFontPath) || !is_dir(self::$trueTypeFontPath)) {
    throw new PHPExcel_Exception('Valid directory to TrueType Font files not specified');
}
```

the deep reason is that `PHPExcel_Shared_Font::$trueTypeFontPath` was newer set, `PHPExcel_Shared_Font::setTrueTypeFontPath()` never called

**Comment by christhomas** [comment] 2016-01-13 16:34
is this fix being merged anytime soon? I don't want to create a branch just to have this, but there is a bug in 1.8.0 because of issue: https://github.com/PHPOffice/PHPExcel/issues/434

**Comment by Pacoup** [comment] 2016-05-04 02:06
This is not a bug. In order to calculate exact font widths, PHPExcel actually needs fonts to work with.

Before using `setAutoSizeMethod()`, you first need to call `setTrueTypeFontPath()`:

```PHP
PHPExcel_Shared_Font::setTrueTypeFontPath('C:/Windows/Fonts/');
PHPExcel_Shared_Font::setAutoSizeMethod(PHPExcel_Shared_Font::AUTOSIZE_METHOD_EXACT);

foreach (range('A','L') as $column) {
  $objPHPExcel->getActiveSheet()->getColumnDimension($column)->setAutoSize(TRUE);
}
```

- You can use forward slashes, Windows doesn't care
- Don't forget the last slash, PHPExcel does not automatically append it to the final path

However, this is OS-specific, so you may also want to test for Linux, Windows, OS X, and so on:

```PHP
switch (PHP_OS) {
  case 'WINNT':
    PHPExcel_Shared_Font::setTrueTypeFontPath('C:/Windows/Fonts/');
    PHPExcel_Shared_Font::setAutoSizeMethod(PHPExcel_Shared_Font::AUTOSIZE_METHOD_EXACT);
    break;

  case 'Darwin':
    PHPExcel_Shared_Font::setTrueTypeFontPath('/Library/Fonts/');
    PHPExcel_Shared_Font::setAutoSizeMethod(PHPExcel_Shared_Font::AUTOSIZE_METHOD_EXACT);
    break;

  case 'Linux':
    PHPExcel_Shared_Font::setTrueTypeFontPath('/usr/share/fonts/truetype/');
    PHPExcel_Shared_Font::setAutoSizeMethod(PHPExcel_Shared_Font::AUTOSIZE_METHOD_EXACT);
    break;
}

foreach (range('A','L') as $column) {
  $objPHPExcel->getActiveSheet()->getColumnDimension($column)->setAutoSize(TRUE);
}
```

But, this will not work, because:

- Font names are different from platform to platform
- PHPExcel expects Windows font names
- PHPExcel expects fonts to be located directly in the specified directory, not in subfolders, as is the case on Linux
- Typical Linux servers won't have fonts like Arial installed

Therefore, a better strategy would be to set `AUTOSIZE_METHOD_EXACT` only on Windows (assuming your production machine runs it):

```PHP
if (PHP_OS == 'WINNT') {
  PHPExcel_Shared_Font::setTrueTypeFontPath('C:\Windows\Fonts');
  PHPExcel_Shared_Font::setAutoSizeMethod(PHPExcel_Shared_Font::AUTOSIZE_METHOD_EXACT);
}

foreach (range('A','L') as $column) {
  $objPHPExcel->getActiveSheet()->getColumnDimension($column)->setAutoSize(TRUE);
}
```

Also note that PHPExcel supports a limited set of fonts for this method:

- Arial
- Calibri
- Courier New
- Comic Sans MS
- Georgia
- Impact
- Liberation Sans
- Lucida Console
- Lucida Sans Unicode
- Microsoft Sans Serif
- Palatino Linotype
- Symbol
- Tahoma
- Times New Roman
- Trebuchet MS
- Verdana

If you try to use an unsupported font like Arial Narrow, the method will fail:

```
Unknown font name "Arial Narrow". Cannot map to TrueType font file - /PHPExcel/Classes/PHPExcel/Shared/Font.php:531
```

The method will also fail if the font can't be found on the server. Not all fonts above come with Windows Server.

You can add new fonts by patching the PHPExcel code:

```diff
diff --git a/PHPExcel/Classes/PHPExcel/Shared/Font.php b/PHPExcel/Classes/PHPExcel/Shared/Font.php
index 8e5b27b..47b9eb6 100644
--- a/PHPExcel/Classes/PHPExcel/Shared/Font.php
+++ b/PHPExcel/Classes/PHPExcel/Shared/Font.php
@@ -72,6 +72,11 @@ class PHPExcel_Shared_Font
        const ARIAL_ITALIC                              = 'ariali.ttf';
        const ARIAL_BOLD_ITALIC                         = 'arialbi.ttf';
 
+       const ARIAL_NARROW                              = 'ARIALN.TTF';
+       const ARIAL_NARROW_BOLD                         = 'ARIALNB.TTF';
+       const ARIAL_NARROW_ITALIC                       = 'ARIALNI.TTF';
+       const ARIAL_NARROW_BOLD_ITALIC                  = 'ARIALNBI.TTF';
+
        const CALIBRI                                   = 'CALIBRI.TTF';
        const CALIBRI_BOLD                              = 'CALIBRIB.TTF';
        const CALIBRI_ITALIC                            = 'CALIBRII.TTF';
@@ -439,6 +444,13 @@ class PHPExcel_Shared_Font
                                );
                                break;
 
+                       case 'Arial Narrow':
+                               $fontFile = (
+                                       $bold ? ($italic ? self::ARIAL_NARROW_BOLD_ITALIC : self::ARIAL_NARROW_BOLD)
+                                                 : ($italic ? self::ARIAL_NARROW_ITALIC : self::ARIAL_NARROW)
+                               );
+                               break;
+
                        case 'Calibri':
                                $fontFile = (
                                        $bold ? ($italic ? self::CALIBRI_BOLD_ITALIC : self::CALIBRI_BOLD)
```

In order to make this platform-independent, you would need to include the font with your application, for example, in a local directory:

```PHP
PHPExcel_Shared_Font::setTrueTypeFontPath('fonts');
PHPExcel_Shared_Font::setAutoSizeMethod(PHPExcel_Shared_Font::AUTOSIZE_METHOD_EXACT);
```

However, this approach is very expensive because the fonts specified by PHPExcel are proprietary fonts redistributed with Windows and Office. In order to include them with your code, you will need to license the fonts for redistribution, which could be quite costly.

It's also impossible to embed fonts in Excel documents, so open fonts are not really an option, unless you're willing / able to convince IT to install them on everyone's computer in your office.

Also remember that this functionality relies entirely on the precision of using font widths that are the same on the server generating the spreadsheet and the client opening the spreadsheet. In other words, if you generate the spreadsheet on a Windows server with the Windows Arial font and open the resulting file in Excel on OS X, your document still won't look correct because the Arial font included in OS X is not the same as the Arial font included in Windows, and even if it was, it will render differently on OS X (I've tested this).

## What about previous versions of PHPExcel?

Before 1.8.1, if you hadn't run `setTrueTypeFontPath()` before setting `setAutoSizeMethod()` to `AUTOSIZE_METHOD_EXACT`, the `getTextWidthPixelsExact()` method in Font.php would simply fail silently and `setAutoSize()` would apply approximate widths, as explained by @sharpensteel.

This is because the code for `PHPExcel_Shared_Font::calculateColumnWidth`, a method called when calculating automatic column widths, looked like this:

```PHP
// Try to get the exact text width in pixels
try {
  // If autosize method is set to 'approx', use approximation
  if (self::$autoSizeMethod == self::AUTOSIZE_METHOD_APPROX) {
    throw new PHPExcel_Exception('AutoSize method is set to approx');
  }

  // Width of text in pixels excl. padding
  $columnWidth = self::getTextWidthPixelsExact($cellText, $font, $rotation);

  // Excel adds some padding, use 1.07 of the width of an 'n' glyph
  $columnWidth += ceil(self::getTextWidthPixelsExact('0', $font, 0) * 1.07); // pixels incl. padding

} catch (PHPExcel_Exception $e) {
  // Width of text in pixels excl. padding, approximation
  $columnWidth = self::getTextWidthPixelsApprox($cellText, $font, $rotation);

  // Excel adds some padding, just use approx width of 'n' glyph
  $columnWidth += self::getTextWidthPixelsApprox('n', $font, 0);
}
```

Assuming we didn't run `setTrueTypeFontPath()`, the next method, `getTextWidthPixelsExact()`, would call `getTrueTypeFontFileFromFont()` which itself would `throw`, but because `getTextWidthPixelsExact()` is called from within a `try` block, PHP would catch the `throw` and the function would go on with `getTextWidthPixelsApprox()` in the `catch` block.

So even though you didn't get any errors, it didn't actually work and the column sizes would be approximate, which probably explains https://github.com/PHPOffice/PHPExcel/issues/853.

In 1.8.1, the code now looks like this:

```PHP
// Try to get the exact text width in pixels
$approximate = self::$autoSizeMethod == self::AUTOSIZE_METHOD_APPROX;
if (!$approximate) {
  $columnWidthAdjust = ceil(self::getTextWidthPixelsExact('n', $font, 0) * 1.07);
  try {
    // Width of text in pixels excl. padding
    // and addition because Excel adds some padding, just use approx width of 'n' glyph
    $columnWidth = self::getTextWidthPixelsExact($cellText, $font, $rotation) + $columnWidthAdjust;
  } catch (PHPExcel_Exception $e) {
    $approximate = true;
  }
}

if ($approximate) {
  $columnWidthAdjust = self::getTextWidthPixelsApprox('n', $font, 0);
  // Width of text in pixels excl. padding, approximation
  // and addition because Excel adds some padding, just use approx width of 'n' glyph
  $columnWidth = self::getTextWidthPixelsApprox($cellText, $font, $rotation) + $columnWidthAdjust;
}
```

As you can see, the first call to `getTextWidthPixelsExact()` is not within a `try` block, so when `getTextWidthPixelsExact()` calls [`getTrueTypeFontFileFromFont()`](https://github.com/PHPOffice/PHPExcel/blob/372c7cbb695a6f6f1e62649381aeaa37e7e70b32/Classes/PHPExcel/Shared/Font.php#L311), the [throw](https://github.com/PHPOffice/PHPExcel/blob/372c7cbb695a6f6f1e62649381aeaa37e7e70b32/Classes/PHPExcel/Shared/Font.php#L425-L427) properly halts execution and outputs an error.

**Comment by andrew-pause** [comment] 2017-03-06 16:48
This appears to still be broken, at least in the tagged release for 1.8.1. I just attempted to upgrade with composer and was getting this error.

**Comment by Pacoup** [comment] 2017-03-06 22:27
Although all new development has moved to a new project (https://github.com/PHPOffice/PhpSpreadsheet), **this is not a bug**. If you're getting the error, your client code isn't using the API properly.

Yes, the error reporting to could be better, yes, the API could assume some system defaults, but the point is, if you're not setting the font path, even if you had no error before, `setAutoSizeMethod()` never actually worked.

You can upgrade through Composer and fix the error by calling `setTrueTypeFontPath()` before you call `setAutoSizeMethod()`.

Here's an excerpt from a Drupal module I work on:

```PHP
PHPExcel_Shared_Font::setTrueTypeFontPath(DRUPAL_ROOT . '/' . drupal_get_path('module', 'learning_app') . '/fonts/');
PHPExcel_Shared_Font::setAutoSizeMethod(PHPExcel_Shared_Font::AUTOSIZE_METHOD_EXACT);

foreach (range('A','O') as $column) {
  $active_sheet->getColumnDimension($column)->setAutoSize(TRUE);
}
```

There's more details in the first part of my comment above.

**Comment by PowerKiKi** [comment] 2017-03-07 02:01
Thanks @Pacoup for your answer.

**Closed by PowerKiKi** 2017-03-07 02:01 UTC
