### ISSUE TITLE
simplexml_load_file not working after PHPExcel_IOFactory::load call

### ISSUE THREAD

**Issue by LaySoft** [PHPOffice/PHPExcel#1361] opened 2017-11-25 13:22 UTC
I've spent some hours, to find what's the error:

```php
<?php
error_reporting(E_ALL); ini_set('display_errors', TRUE);
require_once '../API/PHPExcel/Classes/PHPExcel/IOFactory.php';
$xls = PHPExcel_IOFactory::load('lufi.xls');
$hiba = '';
set_error_handler(function($errno, $errstr, $errfile, $errline) use (&$hiba) {
	$hiba .= $errstr . PHP_EOL;
});
if (simplexml_load_file('test.xml', NULL, LIBXML_NOCDATA)) {
	echo 'xml OK' . PHP_EOL;
} else {
	echo $hiba;
	echo 'xml ERROR' . PHP_EOL;
}
```

This gives simplexml_load_file(): I/O warning : failed to load external entity "test.xml" error. If i comment out the $xls = PHPExcel_IOFactory::load('lufi.xls'); line, everything good, xml opened. How can I solve this?

**Comment by PowerKiKi** [comment] 2017-11-25 13:51
Duplicate of https://github.com/PHPOffice/PhpSpreadsheet/issues/74, migrate to PhpSpreadsheet to solve it.

**Closed by PowerKiKi** 2017-11-25 13:51 UTC
