### ISSUE TITLE
After upgrading to PHP 5.6.29, using SQLite3 cache method does not generate records in excel file

### ISSUE THREAD

**Issue by lourdas** [PHPOffice/PHPExcel#1085] opened 2016-12-12 08:54 UTC
After upgrading to PHP 5.6.29 in my server (from 5.6.28 using the dotdeb repository), PHPExcel generates empty Excel files when using SQLite3 cache method. If I disable the caching method, it works, the Excel file is as expected.

**Comment by robertharm** [comment] 2016-12-23 11:53
same issue here. When using SQLite3 as caching mechanism, I am getting the following error in my WordPress plugin "Maps Marker Pro":

`Fatal error: Call to a member function setValue() on null in /PHPExcel/Worksheet.php on line 1095`
or
`Fatal error: Call to a member function getXfIndex() on null in /PHPExcel/Style.php on line 412`

If I try it again several times, sometimes these errors do not occur and a file is created - anyway as @lourdas describes, this file is also empty.

Any input on how to solve this would be appreciated!

**Comment by schultz-it-solutions** [comment] 2017-01-18 13:35
same here - this took me days to pin down!

PHP 5.6.29 with
SQLite3 support	enabled
SQLite3 module version 	0.7-dev
SQLite Library 	3.8.10.2 

Creating worksheets with Caching method SQLite3 produces the correct number of colums and rows, but each cell is empty. When I switch to method "in PHP memory" all runs as expected.

If requested, I can provide an showcase environment

Best regards
Ruediger Schultz

**Comment by PowerKiKi** [comment] 2017-01-18 13:40
It would be great if one of you were able to contribute a PR against PhpSpreadsheet develop branch to fix this issue. I am afraid I won't have much time to investigate this one.

**Comment by schultz-it-solutions** [comment] 2017-01-18 13:45
I'll try to investigate and see what I can do...

**Comment by schultz-it-solutions** [comment] 2017-01-18 14:10
Seems to me to be caused by
https://bugs.php.net/bug.php?id=73530 , which is scheduled to be reverted in PHP 5.6.30:

[2017-01-13 10:39 UTC] cmb@php.net
The revert of the BC breaking commit is already in PHP 5.6.30RC1,
and as such is supposed to be shipped with PHP 5.6.30.

So I will evaluate this PHP release and get back here...

**Comment by schultz-it-solutions** [comment] 2017-01-20 15:06
In my environment the PHP 5.6.30 **successfully fixes this issue** (although PHP 5.6.30RC1 seemed not to).
so I suggest to close this issue

**Comment by PowerKiKi** [comment] 2017-01-20 15:19
Thank you for reporting back your findings. Closing as requested.

**Closed by PowerKiKi** 2017-01-20 15:19 UTC
Labels: Type - Bug

**Comment by schultz-it-solutions** [comment] 2017-01-30 08:40
@PowerKiKi: just a thought on this CLOSED issue here.
Could there be a respective note in PHPExcel and PhpSpreadsheet, that with PHP 5.6.29 there is a bug regarding the caching method SQLite3, so people do not tap into this trap?
Warm regards
Ruediger

**Comment by PowerKiKi** [comment] 2017-01-31 12:26
I think it's a good idea, but I am not sure how to do it. I've been
thinking about excluding this PHP version via composer.json, but that may
be excessive for people who don't even use SQLite. Maybe throwing an
exception from our code when enabling SQLite ? Or only a mention in the doc
?

Whatever we choose to do, it should only be done for PhpSpreadsheet, not
PHPExcel.

**Comment by schultz-it-solutions** [comment] 2017-01-31 13:59
To be frank, I do not think we need some messures "within the code". PHP 5.6.29 is already "not-the-latest-one", so the issue will occur "less-and-less". 
maybe a note in **readme.md in the "Requirements" section** would be enough? 
I know you are already fully focused on PhpSpreadsheet, but as long as there is no stable release (do you have a timeframe for this by the way???), copying such a note back to PHPExcel would be great...

**Comment by lourdas** [comment] 2017-01-31 18:15
I agree with @schultz-it-solutions. PHP is now on 5.6.30. A warning message in the documentation/guide should be enough.

**Comment by PowerKiKi** [comment] 2017-02-01 08:39
I agree with the suggestion to only mention it in the docs. Could one of
you suggest a PR please ? I'll merge them (for PHPExcel and PhpSpreadsheet)

**Comment by schultz-it-solutions** [comment] 2017-02-01 09:27
I'm afraid I am not very knowledgable about the processes here on github. I tried to create an PR, but am not sure whether this was correctly done...

**Comment by PowerKiKi** [comment] 2017-02-14 05:34
Thank you for the suggestion, I merged a variation in PHPExcel and PhpSpreadsheet.
