### ISSUE TITLE
Opening Password Protected Excel File

### ISSUE THREAD

**Issue by arjereza** [PHPOffice/PHPExcel#1369] opened 2017-12-11 03:32 UTC
Hi,

Is there a way to open/read/import a password protected excel file using PHPExcel?  I am trying to automate reading an excel file then uploading it to a database.  One of the requirements is to be able to open a password protected file.

Any help will be appreciated.

Thanks.

**Comment by arjereza** [comment] 2017-12-27 06:12
Anyone?

Thanks.

**Comment by PowerKiKi** [comment] 2017-12-27 08:08
Duplicate of #942

**Closed by PowerKiKi** 2017-12-27 08:08 UTC
