### ISSUE TITLE
Syntax Error in functions.php line 581 -->  'break' not in the 'loop' or 'switch' context 

### ISSUE THREAD

**Issue by vusisindane** [PHPOffice/PHPExcel#1379] opened 2017-12-20 10:25 UTC
I'm not sure if there's a newer version but this refers to version 1.8.0.
Look at the file below:
PHPExcel/Calculations/functions.php... line 581.  There is a syntax error.
**'break' not in the 'loop' or 'switch' context**

**Comment by PowerKiKi** [comment] 2017-12-21 02:20
Duplicate of #1296

**Closed by PowerKiKi** 2017-12-21 02:20 UTC

**Comment by PowerKiKi** [comment] 2017-12-21 02:23
Duplicate of #1247,  #1084, #642, #1095
