### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by amorZhu** [PHPOffice/PHPExcel#1406] opened 2018-05-11 10:48 UTC
Fatal error: 'break' not in the 'loop' or 'switch' context in vendor/phpoffice/phpexcel/Classes/PHPExcel/Calculation/Functions.php on line 581

**Comment by PowerKiKi** [comment] 2018-08-06 04:45
Duplicate of #1296, #1247, #1084, #642, #1095

**Closed by PowerKiKi** 2018-08-06 04:45 UTC
