### ISSUE TITLE
stupid README at project superset

### ISSUE THREAD

**Issue by mckaygerhard** [PHPOffice/PHPExcel#1175] opened 2017-04-06 22:50 UTC
https://github.com/PHPOffice/PhpSpreadsheet/issues/134

PHPExcel will no longer be maintained
but.. " PhpSpreadsheet is still unstable and not yet released"
oh men! of course! I UNDERSTAND! ITS CLARELLY CLEAR!????

and takin in consideration the "php until next release" tha forces the admin mantainers constant builds.. wthf!

i quoted te README at https://github.com/PHPOffice/PhpSpreadsheet/blob/ea5663bc005bcd0277ca18e563b305fe3151b3a4/README.md:

>Because all efforts have shifted to PhpSpreadsheet, PHPExcel will no longer be maintained. All contributions for PHPExcel, patches and new features, should target PhpSpreadsheet develop branch.

later said:

>However PhpSpreadsheet is still unstable and not yet released. So if you need stability stick to PHPExcel until this project is released. If you prefer to live on the edge you can try to install this project manually via composer, but there is no guarantee and it will likely break again before an official release.

so then:

**Comment by PowerKiKi** [comment] 2017-04-07 02:19
Closing as duplicate of https://github.com/PHPOffice/PhpSpreadsheet/issues/134

**Closed by PowerKiKi** 2017-04-07 02:19 UTC
