### ISSUE TITLE
Problems when using PHP native round() function

### ISSUE THREAD

**Issue by MarcosBL** [PHPOffice/PHPExcel#237] opened 2013-08-21 10:26 UTC
I know this is weird but... isolating this code:

``` php
require_once dirname(__FILE__) . '/lib/PHPExcel/IOFactory.php';
echo round(68.3499,2).PHP_EOL; // Works
$inputFileType = PHPExcel_IOFactory::identify($inputFileName);
echo $inputFileType.PHP_EOL; // Just to get the file type
echo round(68.3499,2).PHP_EOL; // Works
$objReader = PHPExcel_IOFactory::createReader($inputFileType);
echo round(68.3499,2).PHP_EOL; // Works
$objPHPExcel = $objReader->load($inputFileName);
echo round(68.3499,2).PHP_EOL; // KA-BOM, right after the load() call
```

I get this result:

``` php
68.35
Excel5
68.35
68.35
68.34999999999999
```

Problem starts just after loading the file with the Reader object... PHP 5.3.5-1ubuntu7.11 any idea on what's happening here ? Thanks in advance !

**Comment by aleho** [comment] 2015-09-24 12:38
Adding my 2 cents: Do not set precision (or any ini values). It leads to all kinds of problems and awkward "WTF?" moments for users.

Took us quite some time to find out what was failing us (first expected our code, then the database, then the ORM to be the culprit).

Small test case:
```php
$float          = 5022 + 3570.21;
$savedPrecision = ini_get('precision');
$setPrecision   = (PHP_INT_SIZE == 4) ? 14 : 16;

echo "current=$savedPrecision\n";          // current=14
echo $float . "\n";                        // 8592.21
echo round($float, 2) . "\n\n";            // 8592.21

if ($savedPrecision < $setPrecision) {
    ini_set('precision', $setPrecision);
}
$iniSet = ini_get('precision');

echo "set=$setPrecision, ini=$iniSet\n";   // set=16, ini=16
echo $float . "\n";                        // 8592.209999999999
echo round($float, 2) . "\n";              // 8592.209999999999
```

As you can see in the comments, the output is completely wrong as ```$float``` should only be a float with 2 decimals. Obviously, a precision of 16 is too high to be handled by our x86_64 environment.

**Comment by Lewiscowles1986** [comment] 2015-09-24 12:51
Still... do not use floating point numbers for spreadsheet numbers! Also do not follow my advices of sprintf unless you have a specific use-case...

Use `bc_math` library, it's geared for this and does not involve any twiddling of php ini settings at runtime

**Comment by aleho** [comment] 2015-09-24 13:31
@Lewiscowles1986 I've never been fiddling with precision in php_ini. PHPExcel is.
What I actually meant: As soon as you initialize a PHPExcel instance, code throughout your whole application may break (like adding two arbitrary numbers).

**Comment by Lewiscowles1986** [comment] 2015-09-24 13:34
Oh, I'm not sure if you missed it, the code above definitely fiddles with php precision using ini set (which AFAIK is not cacheable, and represents both bad practice, and concern if the code is run more than a few times)

**Comment by aleho** [comment] 2015-09-24 14:21
@Lewiscowles1986 The snippet I posted above? It's a short sample meant for reproducing the bugs we were facing. See [Calculation.php, line 2076](https://github.com/PHPOffice/PHPExcel/blob/681c30b2ea3871ba8d9e484b4400edccba377ee0/Classes/PHPExcel/Calculation.php#L2076).

**Comment by Lewiscowles1986** [comment] 2015-09-24 14:57
@aleho please do not take this the wrong way, I respect that we all have our own path; but IMHO, you do not need to reproduce this bug. 

Firstly, it's not specifically a bug in PHPExcel, it's a side-effect of the data structures, and runtime used. I propose changing this. Secondly, there is already an external library that can mitigate this issue entirely without needing to run any new tests, maybe even being able to drop some.

I Fully understand that reproducing bugs is part of the cycle of issuing fixes, and being a good developer; and that sometimes this can mean simplifying the representation to demonstrate an issue. 

There are, a few select situations however (of which I am confident this represents at least two), where you can look at code, put down the tools, and issue a :warning: until the issue is resolved. 

 * Floating point numbers are are problematic in terms of accuracy, and consistency

***See below***

```php
        $setPrecision = (PHP_INT_SIZE == 4) ? 14 : 16;
```

 * You are modifying at runtime, the entire runtime-environment instance; for the duration of script execution, because floating-point-precision setting per-call, takes up more resources, and results in poorer performance. The problem is that you are trying to out-engineer an over-engineered solutions... Each time you address a different use-case, complexity will increase, and performance will fall; until you eventually have to settle for re-implementing an existing library. 

Using `bc_math` is a drop-in for fixing this. This is my whole point.

**Comment by aleho** [comment] 2015-09-24 15:15
The result of the operation ```(5022 + 3570.21)``` should always be ```8592.21```. On 16, 32 and 64 bit systems. Float or none, we're not talking about ultra-high precision operations were errors are to be expected.

If you're using a PHP library that sets runtime so that arbitrary additions break in all code executed afterwards, this is a bug. This is not platform-specific breakage. It doesn't matter whether PHP allows you to change settings at runtime that break code. *Any* code executed after modifying 'precision' in such a way demonstrated above will break, in any library or code you're using.

```You are modifying at runtime, the entire runtime-environment instance; for the duration of script execution```
No. I'm not and we were not. PHPExcel is. Again, I'm not touching ini-settings. PHPExcel is, every time after instantiating.

Apart from that the code in PHPExcel is wrong anyway, the precision is set to a value that can't be satisfied correctly.

**Comment by atlantis** [comment] 2015-12-18 07:45
This just bit us, too - after instantiating a single PHPExcel object, a few lines later round(85.43, 2) outputs 85.43000000000001.  I see the attempt to clean it up in the destructor, but the problem is that during the lifetime of any PHPExcel object, the state entire PHP engine is modified.  So rounding values you're feeding into PHPExcel isn't cool (once you've saved/outputted your spreadsheet and destroyed the PHPExcel object, everything's good again - but by then you're probably done processing the request anyway).

Interestingly, on our particular version of PHP (5.6.14-0+deb8u1), the default precision is 14 and round() loses its :hankey: for any INI precision value greater than 15.  So for now we're just commenting out PHPExcel's modification of the precision.

**Comment by hmhofman** [comment] 2017-02-02 15:35
So. It has been what? 3.6 years? Is this problem fixed already? 
My database queries broke because of this error. 
Reading the final comments are more than 1 year old, I figured this would be fixed.
Not so for php 5.5.9 (Ubuntu 14.04) 
Wait! Not for php 7.1.1 (Arch build: Jan 18 2017)

**Comment by Lewiscowles1986** [comment] 2017-02-02 15:42
@hmhofman I'm sure they would appreciate your fix submitted with tests via PR. Please do not treat this like a sweet-shop.

**Comment by MarkBaker** [comment] 2017-02-02 19:16
If you pull the develop branch, then you'l find that it was fixed nearly 2 years ago

**Comment by Lewiscowles1986** [comment] 2017-02-02 22:11
@MarkBaker any reason it hasn't been merged? That seems strange, like there could be issues

**Comment by PowerKiKi** [comment] 2017-02-02 23:00
Closing because it should be fixed in PhpSpreadsheet according to Mark

**Closed by PowerKiKi** 2017-02-02 23:00 UTC
Labels: Type - Bug

**Comment by MarkBaker** [comment] 2017-02-03 00:29
It's in the develop branch; master is for production releases.... the "issue" is time
