### ISSUE TITLE
Bug in Excel2007/Worksheet.php in count function

### ISSUE THREAD

**Issue by alefbox** [PHPOffice/PHPExcel#1404] opened 2018-04-26 09:32 UTC
There is a bug in line 771 in PHPExcel/Writer/Excel2007/Worksheet.php file

https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Writer/Excel2007/Worksheet.php#L771 
count($columns > 0) - wrong closed scope place, it must be count($columns) > 0

In php 7.2 this causes Countable error

**Comment by PowerKiKi** [comment] 2018-04-26 11:26
Duplicate of #1334

**Comment by PowerKiKi** [comment] 2018-04-26 11:27
Duplicate of #1376

**Closed by PowerKiKi** 2018-04-26 11:26 UTC
