### ISSUE TITLE
ODD - Cant initialize SoapClient after loading sheet

### ISSUE THREAD

**Issue by xxnoobmanxx** [PHPOffice/PHPExcel#1221] opened 2017-05-25 17:10 UTC
I am trying to import some data from an excel file through a webservice. When I connect to the webservice after `PHPExcel_Reader_Excel2007->load` method, it will throw the following Exception:

_* I will keep the webservice address private for security reasons_

```
Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webservice...com/service.svc?wsdl' : failed to
 load external entity "https://webservice...com/service.svc?wsdl"
```

Here is the code:

```
//Load data
$objReader = new PHPExcel_Reader_Excel2007();
$objReader->setReadDataOnly(true);
$objPHPExcel = $objReader->load(__DIR__.'/import_data.xslx'); // Can't connect to webservice after this point
$objPHPExcel->setActiveSheetIndex(0);
$objWorksheet = $objPHPExcel->getActiveSheet();

$entries = [];
//Proccess data and append it to $entries list...

//Connect
$url = "https://webservice...com/service.svc?wsdl";
$ws = new \SoapClient($url, [
    'login' => 'USERNAME',
    'password' => '******',
    'trace' => 1,
    'exception' => 0,
]);

//Send
foreach ($entries as $entry) {
    $ws->UpdateProduct($entry);
}
```

If I connect to the webservice _before_ `$objPHPExcel = $objReader->load...` it will work fine

**Comment by PowerKiKi** [comment] 2017-05-25 20:24
Duplicate of https://github.com/PHPOffice/PhpSpreadsheet/issues/74 and solved in https://github.com/PHPOffice/PhpSpreadsheet/pull/113/commits/6a0a5d9cefbd91365f92ec13288e70146c62e7dc

**Closed by PowerKiKi** 2017-05-25 20:24 UTC

**Comment by xxnoobmanxx** [comment] 2017-05-26 11:51
@PowerKiKi Is that fix released?

**Comment by PowerKiKi** [comment] 2017-05-26 16:29
Unfortunately, it is not yet released
